version: "3"
services:
  node:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    command: ["/workdir/_build/emqx/rel/emqx/bin/emqx", "foreground"]
    # command: ["tail", "-f", "/dev/null"]
    volumes:
      - "./src:/workdir/src"
      - "./apps:/workdir/apps"
      - "./emqx.dev.conf:/workdir/_build/emqx/rel/emqx/etc/emqx.conf"
      - "./emqx_web_hook.dev.conf:/workdir/_build/emqx/rel/emqx/etc/plugins/emqx_web_hook.conf"
      - "./loaded_plugins.dev:/workdir/_build/emqx/rel/emqx/data/loaded_plugins"
    ports:
      - "18083:18083"
      - "8083:8083"
  bench:
    image: emqx/emqtt-bench:0.4
    entrypoint: ["tail", "-f", "/dev/null"]
